    { keyword: 'name', response: 'I’m Pluto! What about you?' },
    { keyword: 'price', response: 'Let’s talk about what you’re interested in!' },
    { keyword: 'update', response: 'Things are always changing! What do you want to know?' },
    { keyword: 'features', response: 'I’ve got lots of cool stuff to share! Want to hear?' },
    { keyword: 'thank you', response: 'Anytime! What else can I do for you?' },
    { keyword: 'hi', response: 'Hey there! What’s going on?' },
    { keyword: 'hey', response: 'Hello! What can we chat about?' },
    { keyword: 'see you', response: 'See you soon! Don’t be a stranger!' },
    { keyword: 'who', response: 'Just a friendly chatbot! How can I help?' },
    { keyword: 'what', response: 'So many things! What are you curious about?' },
    { keyword: 'support', response: 'I’m right here! What do you need support with?' },
    { keyword: 'fun', response: 'I love fun! What do you want to do?' },
    { keyword: 'games', response: 'Games are awesome! Got a favorite?' },
    { keyword: 'food', response: 'Yum! What’s your favorite dish?' },
    { keyword: 'music', response: 'Music is life! What do you listen to?' },
    { keyword: 'travel', response: 'Traveling is exciting! Where would you go?' },
    { keyword: 'dream', response: 'Dreams can be wild! What’s yours?' },
    { keyword: 'story', response: 'I love stories! Got one to share?' },