    { keyword: /can you (.+)/i, response: (matches) => `What do you want me to do about ${matches[1]}?` },
    { keyword: /I'm not sure/i, response: () => `Uncertainty is part of life. What’s confusing you?` },
    { keyword: /that sounds (.+)/i, response: (matches) => `Why does it sound ${matches[1]} to you?` },
    { keyword: /sometimes/i, response: () => `What do you feel sometimes?` },
    { keyword: /always/i, response: () => `What does always mean to you?` },
    { keyword: /never/i, response: () => `What makes you say never?` },
    { keyword: /maybe/i, response: () => `What makes you uncertain about that?` },
    { keyword: /I enjoy (.+)/i, response: (matches) => `What do you enjoy most about ${matches[1]}?` },
    { keyword: /I feel like (.+)/i, response: (matches) => `What leads you to feel like ${matches[1]}?` },
    { keyword: /it is (.+)/i, response: (matches) => `What makes it ${matches[1]}?` },
    { keyword: /I'm (.+)/i, response: (matches) => `What does being ${matches[1]} mean to you?` },
    { keyword: /you think (.+)/i, response: (matches) => `What do you think I should think about ${matches[1]}?` },
    { keyword: /I don't know/i, response: () => `That’s okay! What do you want to know?` },
    { keyword: /I cannot (.+)/i, response: (matches) => `Why do you feel you cannot ${matches[1]}?` },
    { keyword: /it seems (.+)/i, response: (matches) => `What makes it seem ${matches[1]} to you?` },
    { keyword: /I hope (.+)/i, response: (matches) => `Hope is powerful! What do you hope for?` },
    { keyword: /I try (.+)/i, response: (matches) => `Trying is important! What do you try to ${matches[1]}?` },
    { keyword: /I believe (.+)/i, response: (matches) => `Beliefs shape us. Why do you believe ${matches[1]}?` },
    { keyword: /I want to know (.+)/i, response: (matches) => `What do you hope to learn about ${matches[1]}?` },
    { keyword: /I wonder (.+)/i, response: (matches) => `Wondering is part of curiosity! What do you wonder about ${matches[1]}?` },
    { keyword: /I can't (.+)/i, response: (matches) => `Why do you think you can’t ${matches[1]}?` },
    { keyword: /I need help with (.+)/i, response: (matches) => `What kind of help do you need with ${matches[1]}?` },
    { keyword: /I feel good/i, response: () => `That’s great! What makes you feel good?` },
    { keyword: /I feel bad/i, response: () => `I’m sorry to hear that. What’s bothering you?` },
    { keyword: /I often (.+)/i, response: (matches) => `What do you often do when you ${matches[1]}?` },
    { keyword: /tell me more about (.+)/i, response: (matches) => `I’m all ears! What more can you share about ${matches[1]}?` },
    { keyword: /I regret (.+)/i, response: (matches) => `Regret can be heavy. What do you regret about ${matches[1]}?` },
    { keyword: /I appreciate (.+)/i, response: (matches) => `Appreciation is key! What do you appreciate about ${matches[1]}?` },
    { keyword: /I notice (.+)/i, response: (matches) => `Noticing is important! What do you notice about ${matches[1]}?` },
    { keyword: /I see (.+)/i, response: (matches) => `What do you see that makes you feel ${matches[1]}?` },
    { keyword: /I compare (.+)/i, response: (matches) => `Comparison can be tricky. What do you compare ${matches[1]} to?` },
    { keyword: /I'm excited/i, response: () => `Excitement is wonderful! What’s making you excited?` },
    { keyword: /I'm bored/i, response: () => `Boredom can be tough. What would you like to do?` },
    { keyword: /I'm tired/i, response: () => `Rest is important. What makes you feel tired?` },
    { keyword: /I feel overwhelmed/i, response: () => `That can be difficult. What’s overwhelming you?` },
    { keyword: /I'm curious/i, response: () => `Curiosity is great! What are you curious about?` },
    { keyword: /I appreciate you/i, response: () => `Thank you! What do you appreciate the most?` },
    { keyword: /I have trouble with (.+)/i, response: (matches) => `What kind of trouble do you have with ${matches[1]}?` },
    { keyword: /I experience (.+)/i, response: (matches) => `Experiences shape us. What do you experience with ${matches[1]}?` },
    { keyword: /I enjoy talking to you/i, response: () => `I enjoy talking to you too! What do you like to chat about?` },
    { keyword: /I think life is (.+)/i, response: (matches) => `What makes you think life is ${matches[1]}?` },
    { keyword: /I often wonder/i, response: () => `Wondering is a sign of curiosity! What do you often wonder about?` },
];

const additionalKeywords = [    { keyword: 'hello', response: 'Hi there! What’s up?' },
    { keyword: 'help', response: 'I’m here for you! What do you need?' },
    { keyword: 'thanks', response: 'You got it! Anything else on your mind?' },
    { keyword: 'bye', response: 'Catch you later! Take care!' },
    { keyword: 'sorry', response: 'No worries! What’s bothering you?' },