    { keyword: 'success', response: 'Success is subjective! What does it mean to you?' },
    { keyword: 'inspiration', response: 'Inspiration can come from anywhere! What inspires you?' },
    { keyword: 'happiness', response: 'Happiness is key! What makes you happy?' },
    { keyword: 'friendship', response: 'Friendship is special! Who’s your best friend?' },
    { keyword: 'family', response: 'Family is important! Tell me about yours.' },
    { keyword: 'future', response: 'The future is exciting! What are your hopes for it?' },
    { keyword: 'past', response: 'The past shapes us! What’s a lesson you’ve learned?' },
    { keyword: 'change', response: 'Change can be hard! What’s something you want to change?' },
    { keyword: 'advice', response: 'Advice can be helpful! What do you need advice on?' },
    { keyword: 'question', response: 'Questions lead to answers! What’s your question?' },
    { keyword: 'wisdom', response: 'Wisdom is valuable! What’s a piece of wisdom you cherish?' },
    { keyword: 'knowledge', response: 'Knowledge is power! What do you want to learn more about?' },