    { keyword: 'adventure', response: 'Adventures are the best! What’s your dream trip?' },
    { keyword: 'art', response: 'Art is beautiful! Do you create or appreciate it?' },
    { keyword: 'fashion', response: 'Fashion is fun! What’s your style?' },
    { keyword: 'science', response: 'Science is fascinating! Do you have a favorite topic?' },
    { keyword: 'history', response: 'History is so rich! What era do you find interesting?' },
    { keyword: 'technology', response: 'Tech is always evolving! What’s your favorite gadget?' },
    { keyword: 'animals', response: 'Animals are amazing! Do you have pets?' },
    { keyword: 'nature', response: 'Nature is so calming! What’s your favorite place outdoors?' },
    { keyword: 'color', response: 'Colors can be so vibrant! What’s your favorite color?' },
    { keyword: 'dreams', response: 'Dreams can be strange! Do you remember yours?' },
    { keyword: 'goal', response: 'Goals are important! What are you aiming for?' },
    { keyword: 'wish', response: 'Wishes are powerful! What’s your biggest wish?' },
    { keyword: 'memories', response: 'Memories are special! What’s your favorite one?' },
    { keyword: 'challenge', response: 'Challenges can be tough! What have you overcome?' },
    { keyword: 'motivation', response: 'What motivates you to keep going?' },